version: 2
updates:

  # PHP Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
      - 'php'
    open-pull-requests-limit: 4
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # Cause a release for non-dev-deps
      prefix: fix(deps)
      # No release for dev-deps
      prefix-development: chore(dev-deps)
    ignore:
      # Ignore major updates for Laravel and Symfony framework components
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "laravel/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "illuminate/*"
        update-types: ["version-update:semver-major"]



  # NPM/Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
      - 'javascript'
    open-pull-requests-limit: 4
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # Cause a release for non-dev-deps
      prefix: fix(deps)
      # No release for dev-deps
      prefix-development: chore(dev-deps)
    ignore:
      # Ignore major updates for common breaking-change-prone packages
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]


  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
      - 'github-actions'
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # GitHub Actions updates are typically infrastructure
      prefix: chore(ci)
      prefix-development: chore(ci)