name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🐘 Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, pdo_mysql, pdo_pgsql, tokenizer, xml, zip
          coverage: none

      - name: 📦 Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 🗂️ Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 🔧 Install PHP dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
        env:
          COMPOSER_AUTH: '{"http-basic": {"nova.laravel.com": {"username": "${{ secrets.NOVA_USERNAME }}", "password": "${{ secrets.NOVA_LICENSE_KEY }}"}}}'

      - name: 🚢 Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME  }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN  }}
          GITHUB_REPOSITORY: ${{ github.repository  }}
        run: npx semantic-release

